create extension if not exists "pgcrypto";

create table if not exists public.retailer_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  phone text not null unique,
  verification_status text not null default 'verified',
  retailer_status text not null default 'lead',
  source_channel text,
  source_detail text,
  store_name text,
  location text,
  first_seen_at timestamptz not null default timezone('utc', now()),
  last_active_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.saved_products (
  id bigint generated by default as identity primary key,
  retailer_id uuid not null references auth.users (id) on delete cascade,
  product_id text not null,
  product_slug text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (retailer_id, product_slug)
);

create table if not exists public.activity_events (
  id bigint generated by default as identity primary key,
  retailer_id uuid references auth.users (id) on delete set null,
  event_type text not null,
  product_id text,
  product_slug text,
  source_channel text,
  page_path text,
  metadata jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.retailer_profiles enable row level security;
alter table public.saved_products enable row level security;
alter table public.activity_events enable row level security;

create policy "Retailers can read own profile"
on public.retailer_profiles
for select
to authenticated
using (auth.uid() = id);

create policy "Retailers can insert own profile"
on public.retailer_profiles
for insert
to authenticated
with check (auth.uid() = id);

create policy "Retailers can update own profile"
on public.retailer_profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Retailers can read own saved products"
on public.saved_products
for select
to authenticated
using (auth.uid() = retailer_id);

create policy "Retailers can insert own saved products"
on public.saved_products
for insert
to authenticated
with check (auth.uid() = retailer_id);

create policy "Retailers can delete own saved products"
on public.saved_products
for delete
to authenticated
using (auth.uid() = retailer_id);

create policy "App can insert activity events"
on public.activity_events
for insert
to anon, authenticated
with check (true);
